### ISSUE TITLE
Could JACK(/LV2) "CV" be supported?

### ISSUE THREAD

**Issue by mxmilkiib** [BlokasLabs/pisound#10]
The JACK system (along with the LV2 plugin format) has support for passing audio rate parameter control "CV" signals between apps (and plugins) for uses including gate/triggers and modulation.

This port type ("CV" in JACK, "CVPort" in LV2) has more recently started seeing support in various software projects. More details on the subject can be found on [this post](https://linuxmusicians.com/viewtopic.php?f=1&t=20701).

Might this be something that could be supported in a future iteration of pisound?

**Comment by gtrainavicius** [comment]
Hi, are you suggesting using Pisound's stereo input and output ports for CV, or adding new hardware ports dedicated to CV on the board?

**Comment by mxmilkiib** [comment]
I guess it depends if the current ports are DC coupled or not. If not, possibly something maybe the further than sooner future.

**Comment by mxa** [comment]
> I guess it depends if the current ports are DC coupled or not. If not, possibly something maybe the further than sooner future.

According to the docs only the output is DC coupled https://blokas.io/pisound/docs/Audio/

**Comment by gtrainavicius** [comment]
> According to the docs only the output is DC coupled https://blokas.io/pisound/docs/Audio/

Correct, and the input is AC coupled. The audio output voltage range does not cover the full CV control range however, so additional scale and shift circuitry would be necessary to enable Pisound output to be used for CV in its full range.

**Comment by mxmilkiib** [comment]
I've just seen [this video](https://www.youtube.com/watch?v=VEXiezcEOU4) which demonstrates possibilities with AC-coupled interfaces.

**Comment by gtrainavicius** [comment]
Closing this issue, discussion could be continued on https://community.blokas.io :)
