### ISSUE TITLE
Install and use pisound on Jetson Nano

### ISSUE THREAD

**Issue by mpariente** [BlokasLabs/pisound#11]
Hi,

Would you be aware of a way to use pisound on the [Jetson Nano](https://developer.nvidia.com/embedded/jetson-nano-developer-kit) (aarch64) ? That would be amazing !

**Comment by gtrainavicius** [comment]
Pisound wouldn't mount on top of it, due to the massive heatsink. :) But it is possible on GPIO compatible boards to work with Pisound, for example, here are the steps to get it working with Asus Tinkerboard S: https://community.blokas.io/t/pisound-on-tinker-board/1015

**Comment by mpariente** [comment]
Thanks for the quick answer. 
Good news, GPIO pins are the other way around on the Nano, so it physically mounts.



> Pisound wouldn't mount on top of it, due to the massive heatsink. :) But it is possible on GPIO compatible boards to work with Pisound, for example, here are the steps to get it working with Asus Tinkerboard S: https://community.blokas.io/t/pisound-on-tinker-board/1015

I had a look at that but it is still unclear to me if a similar procedure would work for the Nano.

**Comment by gtrainavicius** [comment]
It comes down to having the device tree set up for the board and having the kernel module built and installed. The device tree is the most specific thing that must be ported, the kernel module itself does not depend much on actual hardware it's running on - the device tree is supposed to fill in the details about the current environment the module is in.

**Comment by mpariente** [comment]
Ok, thank you very much for the quick answer. 
I'm pretty much lost with these things but I'll give it a try. 
I'm closing for now and I'll keep you posted if you're interested.
